import type { AuditCycle, AuditAsset, Auditor, Discrepancy } from "./types";

export const MOCK_CYCLES: AuditCycle[] = [
  {
    id: "AC-005",
    name: "IT Department Q3 2026 Audit",
    departmentScope: "Engineering",
    locationScope: "Floor 3, Wing A",
    startDate: "2026-07-01",
    endDate: "2026-07-31",
    status: "Active",
    totalAssets: 8,
    verifiedCount: 3,
    discrepanciesCount: 1,
    createdBy: "Asset Manager",
    notes: "Comprehensive audit of all IT equipment in Engineering wing",
  },
  {
    id: "AC-004",
    name: "Operations Floor Audit",
    departmentScope: "Operations",
    locationScope: "Production Floor, Bay 7",
    startDate: "2026-06-01",
    endDate: "2026-06-15",
    status: "Completed",
    totalAssets: 12,
    verifiedCount: 10,
    discrepanciesCount: 2,
    createdBy: "Asset Manager",
    notes: "Audit of production floor equipment",
  },
  {
    id: "AC-003",
    name: "Finance Department Audit",
    departmentScope: "Finance",
    locationScope: "Floor 2, Wing B",
    startDate: "2026-05-01",
    endDate: "2026-05-15",
    status: "Closed",
    totalAssets: 6,
    verifiedCount: 5,
    discrepanciesCount: 1,
    createdBy: "Asset Manager",
    notes: "Annual finance department asset verification",
  },
  {
    id: "AC-002",
    name: "Warehouse Inventory Audit",
    departmentScope: "Operations",
    locationScope: "Warehouse A",
    startDate: "2026-03-01",
    endDate: "2026-03-15",
    status: "Closed",
    totalAssets: 4,
    verifiedCount: 3,
    discrepanciesCount: 1,
    createdBy: "Asset Manager",
    notes: "Warehouse machinery and equipment verification",
  },
  {
    id: "AC-006",
    name: "Marketing Assets Review",
    departmentScope: "Marketing",
    locationScope: "Floor 3, Wing B",
    startDate: "2026-07-15",
    endDate: "2026-08-15",
    status: "Draft",
    totalAssets: 5,
    verifiedCount: 0,
    discrepanciesCount: 0,
    createdBy: "Asset Manager",
    notes: "Scheduled audit for marketing department AV equipment",
  },
];

export const MOCK_AUDIT_ASSETS: AuditAsset[] = [
  // Active cycle (AC-005)
  { id: "AA-001", cycleId: "AC-005", assetTag: "AR-000001", assetName: 'MacBook Pro 16"', currentLocation: "Floor 3, Wing A", recordedHolder: "Sarah Chen", department: "Engineering", assignedAuditor: "Raj Deshmukh", result: "Verified", verifiedAt: "2026-07-02T10:00:00Z", notes: "Asset in good condition, matched records" },
  { id: "AA-002", cycleId: "AC-005", assetTag: "AR-000010", assetName: "Standing Desk Ergo Pro", currentLocation: "Floor 3, Wing A", recordedHolder: "—", department: "Engineering", assignedAuditor: "Raj Deshmukh", result: "Verified", verifiedAt: "2026-07-03T14:00:00Z", notes: "Available, no issues found" },
  { id: "AA-003", cycleId: "AC-005", assetTag: "AR-000012", assetName: "Server Dell PowerEdge R750", currentLocation: "Server Room, Rack 4", recordedHolder: "Raj Deshmukh", department: "Engineering", assignedAuditor: "Raj Deshmukh", result: "Verified", verifiedAt: "2026-07-04T09:00:00Z", notes: "Running, RAID warning noted separately" },
  { id: "AA-004", cycleId: "AC-005", assetTag: "AR-000016", assetName: "3D Printer Ultimaker S7", currentLocation: "Innovation Lab, Room 301", recordedHolder: "—", department: "Engineering", assignedAuditor: "Raj Deshmukh", result: "Damaged", verifiedAt: "2026-07-05T11:00:00Z", notes: "Extruder clogged, nozzle damaged. Needs maintenance." },
  { id: "AA-005", cycleId: "AC-005", assetTag: "AR-000019", assetName: "Retired Dell OptiPlex 7080", currentLocation: "Storage Room B2", recordedHolder: "—", department: "IT", assignedAuditor: "Raj Deshmukh", result: null, verifiedAt: null, notes: "" },
  { id: "AA-006", cycleId: "AC-005", assetTag: "AR-000008", assetName: "HP LaserJet Enterprise M611", currentLocation: "Floor 2, Copy Room", recordedHolder: "—", department: "Finance", assignedAuditor: "Raj Deshmukh", result: null, verifiedAt: null, notes: "" },
  { id: "AA-007", cycleId: "AC-005", assetTag: "AR-000002", assetName: "Dell UltraSharp 27\" Monitor", currentLocation: "Floor 2, Wing B", recordedHolder: "—", department: "Finance", assignedAuditor: "Raj Deshmukh", result: null, verifiedAt: null, notes: "" },
  { id: "AA-008", cycleId: "AC-005", assetTag: "AR-000014", assetName: "Logitech Rally 4K Camera", currentLocation: "Floor 2, Meeting Room B", recordedHolder: "—", department: "Marketing", assignedAuditor: "Raj Deshmukh", result: null, verifiedAt: null, notes: "" },

  // Completed cycle (AC-004)
  { id: "AA-010", cycleId: "AC-004", assetTag: "AR-000003", assetName: "CNC Machine Model X", currentLocation: "Production Floor, Bay 7", recordedHolder: "—", department: "Operations", assignedAuditor: "Kim Tanaka", result: "Verified", verifiedAt: "2026-06-02T09:00:00Z", notes: "Machine shut down for maintenance, location correct" },
  { id: "AA-011", cycleId: "AC-004", assetTag: "AR-000013", assetName: "Forklift Toyota 8FGU25", currentLocation: "Warehouse A", recordedHolder: "Kim Tanaka", department: "Operations", assignedAuditor: "Kim Tanaka", result: "Damaged", verifiedAt: "2026-06-03T11:00:00Z", notes: "Hydraulic leak visible" },
  { id: "AA-012", cycleId: "AC-004", assetTag: "AR-000011", assetName: "Cisco Webex Board Pro 75", currentLocation: "Floor 1, Meeting Room A", recordedHolder: "Jordan Lee", department: "Operations", assignedAuditor: "Kim Tanaka", result: "Verified", verifiedAt: "2026-06-04T10:00:00Z", notes: "Working fine" },
  { id: "AA-013", cycleId: "AC-004", assetTag: "AR-000020", assetName: "Disposal Batch Q1-2026", currentLocation: "Disposed Off-Site", recordedHolder: "—", department: "IT", assignedAuditor: "Kim Tanaka", result: "Verified", verifiedAt: "2026-06-05T09:00:00Z", notes: "Confirmed disposed, certificate on file" },
  { id: "AA-014", cycleId: "AC-004", assetTag: "AR-000018", assetName: "AC Unit Daikin 3HP", currentLocation: "Floor 3, Wing A, Server Room", recordedHolder: "—", department: "Operations", assignedAuditor: "Kim Tanaka", result: "Missing", verifiedAt: "2026-06-06T14:00:00Z", notes: "AC unit not found at recorded location. Moved to maintenance room?" },
];

export const MOCK_AUDITORS: Auditor[] = [
  { name: "Raj Deshmukh", department: "Engineering", assignedCount: 8 },
  { name: "Kim Tanaka", department: "Operations", assignedCount: 5 },
  { name: "Sarah Chen", department: "Engineering", assignedCount: 0 },
];

export const MOCK_DISCREPANCIES: Discrepancy[] = [
  {
    id: "DIS-001", cycleId: "AC-005", cycleName: "IT Department Q3 2026 Audit",
    assetTag: "AR-000016", assetName: "3D Printer Ultimaker S7",
    type: "Damaged", currentLocation: "Innovation Lab, Room 301",
    recordedHolder: "—", department: "Engineering", reportedBy: "Raj Deshmukh",
    reportedAt: "2026-07-05T11:00:00Z",
    recommendedAction: "Create maintenance request for extruder repair",
    status: "Open", resolvedAt: null,
  },
  {
    id: "DIS-002", cycleId: "AC-004", cycleName: "Operations Floor Audit",
    assetTag: "AR-000020", assetName: "Disposal Batch Q1-2026",
    type: "Incorrect Location", currentLocation: "Disposed Off-Site",
    recordedHolder: "—", department: "IT", reportedBy: "Kim Tanaka",
    reportedAt: "2026-06-05T09:00:00Z",
    recommendedAction: "Update records to reflect disposal. Close discrepancy.",
    status: "Resolved", resolvedAt: "2026-06-10T09:00:00Z",
  },
  {
    id: "DIS-003", cycleId: "AC-004", cycleName: "Operations Floor Audit",
    assetTag: "AR-000018", assetName: "AC Unit Daikin 3HP",
    type: "Missing", currentLocation: "Floor 3, Wing A, Server Room",
    recordedHolder: "—", department: "Operations", reportedBy: "Kim Tanaka",
    reportedAt: "2026-06-06T14:00:00Z",
    recommendedAction: "Investigate location. If confirmed missing, update status to Lost.",
    status: "Acknowledged", resolvedAt: null,
  },
  {
    id: "DIS-004", cycleId: "AC-004", cycleName: "Operations Floor Audit",
    assetTag: "AR-000013", assetName: "Forklift Toyota 8FGU25",
    type: "Damaged", currentLocation: "Warehouse A",
    recordedHolder: "Kim Tanaka", department: "Operations", reportedBy: "Kim Tanaka",
    reportedAt: "2026-06-03T11:00:00Z",
    recommendedAction: "Maintenance request already exists (MR-0095). Monitor repair progress.",
    status: "Resolved", resolvedAt: "2026-06-15T09:00:00Z",
  },
];
