import type { MaintenanceRequest, MaintenanceTimelineEvent } from "./types";

export const MOCK_REQUESTS: MaintenanceRequest[] = [
  {
    id: "MR-0091",
    assetTag: "AR-000018",
    assetName: "AC Unit Daikin 3HP",
    reportedBy: "Kim Tanaka",
    department: "Operations",
    issueTitle: "Compressor not cooling",
    issueDescription: "AC unit running but not cooling. Compressor sounds abnormal. Room temperature rising to 32°C despite unit being on for 2 hours.",
    priority: "High",
    category: "Electrical Issue",
    status: "Pending",
    createdAt: "2026-07-08T10:00:00Z",
    approvedAt: null,
    approvedBy: null,
    rejectionReason: null,
    technician: null,
    technicianAssignedAt: null,
    estimatedCompletion: null,
    repairNotes: null,
    spareParts: null,
    progress: null,
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: ["ac-error-photo.jpg"],
  },
  {
    id: "MR-0092",
    assetTag: "AR-000009",
    assetName: 'iPad Pro 12.9"',
    reportedBy: "Priya Sharma",
    department: "Marketing",
    issueTitle: "Screen flickering intermittently",
    issueDescription: "iPad screen flickers randomly, especially when running design apps. Issue started 3 days ago. Restarting helps temporarily.",
    priority: "Medium",
    category: "Hardware Failure",
    status: "Approved",
    createdAt: "2026-07-07T14:30:00Z",
    approvedAt: "2026-07-08T09:15:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "Raj Deshmukh",
    technicianAssignedAt: "2026-07-08T09:30:00Z",
    estimatedCompletion: "2026-07-12",
    repairNotes: "Will run diagnostics first, may need screen replacement if hardware defect confirmed",
    spareParts: "Replacement display assembly (in stock)",
    progress: null,
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: [],
  },
  {
    id: "MR-0093",
    assetTag: "AR-000003",
    assetName: "CNC Machine Model X",
    reportedBy: "Operator",
    department: "Operations",
    issueTitle: "Spindle bearing failure",
    issueDescription: "CNC machine making grinding noise. Spindle vibration detected. Machine has been shut down for safety. Bearing replacement needed.",
    priority: "Critical",
    category: "Hardware Failure",
    status: "Technician Assigned",
    createdAt: "2026-07-05T08:30:00Z",
    approvedAt: "2026-07-05T10:00:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "External - Haas Service",
    technicianAssignedAt: "2026-07-05T14:00:00Z",
    estimatedCompletion: "2026-07-15",
    repairNotes: "On-site visit scheduled for July 10. Bearing kit ordered.",
    spareParts: "Spindle bearing kit, coolant seals",
    progress: null,
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: ["spindle-photo.jpg", "vibration-report.pdf"],
  },
  {
    id: "MR-0094",
    assetTag: "AR-000001",
    assetName: 'MacBook Pro 16"',
    reportedBy: "Sarah Chen",
    department: "Engineering",
    issueTitle: "Battery draining rapidly",
    issueDescription: "Battery goes from 100% to 20% in 45 minutes under normal use. Cycle count shows 847. Possible battery degradation.",
    priority: "Medium",
    category: "Hardware Failure",
    status: "In Progress",
    createdAt: "2026-07-03T11:00:00Z",
    approvedAt: "2026-07-03T14:00:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "Internal - IT Support",
    technicianAssignedAt: "2026-07-04T09:00:00Z",
    estimatedCompletion: "2026-07-10",
    repairNotes: "Battery replacement authorized. New battery in stock.",
    spareParts: "A2451 battery pack",
    progress: "Repair Started",
    workStartedAt: "2026-07-08T10:00:00Z",
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: [],
  },
  {
    id: "MR-0095",
    assetTag: "AR-000013",
    assetName: "Forklift Toyota 8FGU25",
    reportedBy: "Kim Tanaka",
    department: "Operations",
    issueTitle: "Hydraulic leak from mast seal",
    issueDescription: "Hydraulic fluid leaking from mast seals during lift operations. Fluid level dropping. Need seal replacement urgently.",
    priority: "High",
    category: "Physical Damage",
    status: "In Progress",
    createdAt: "2026-07-01T08:00:00Z",
    approvedAt: "2026-07-01T10:00:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "External - Toyota MH",
    technicianAssignedAt: "2026-07-02T09:00:00Z",
    estimatedCompletion: "2026-07-09",
    repairNotes: "Seals ordered from Toyota. Technician visit confirmed for July 8.",
    spareParts: "Mast seal kit, hydraulic fluid",
    progress: "Parts Ordered",
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: ["leak-photo.jpg"],
  },
  {
    id: "MR-0096",
    assetTag: "AR-000008",
    assetName: "HP LaserJet Enterprise M611",
    reportedBy: "Lisa Park",
    department: "Finance",
    issueTitle: "Paper jamming frequently",
    issueDescription: "Printer jams every 10-15 pages. Rollers have been cleaned but issue persists. Possible roller wear.",
    priority: "Low",
    category: "Physical Damage",
    status: "Resolved",
    createdAt: "2026-06-25T09:00:00Z",
    approvedAt: "2026-06-25T11:00:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "Internal - IT Support",
    technicianAssignedAt: "2026-06-26T09:00:00Z",
    estimatedCompletion: "2026-06-30",
    repairNotes: "Pickup rollers replaced, separator pad cleaned.",
    spareParts: "HP roller kit",
    progress: "Completed",
    workStartedAt: "2026-06-28T10:00:00Z",
    resolvedAt: "2026-06-28T14:00:00Z",
    resolutionSummary: "Pickup rollers and separator pad replaced. Test print 200 pages without jam.",
    finalNotes: "Working perfectly. No further action needed.",
    repairCost: 85,
    conditionAfter: "Excellent",
    attachments: [],
  },
  {
    id: "MR-0097",
    assetTag: "AR-000011",
    assetName: "Cisco Webex Board Pro 75",
    reportedBy: "Jordan Lee",
    department: "Operations",
    issueTitle: "Touch screen unresponsive",
    issueDescription: "Bottom third of touch screen does not register input. Firmware restart attempted, no improvement. Physical damage suspected.",
    priority: "Medium",
    category: "Physical Damage",
    status: "Rejected",
    createdAt: "2026-07-06T15:00:00Z",
    approvedAt: null,
    approvedBy: null,
    rejectionReason: "Asset still under warranty. Contact Cisco TAC directly for warranty repair instead of internal maintenance.",
    technician: null,
    technicianAssignedAt: null,
    estimatedCompletion: null,
    repairNotes: null,
    spareParts: null,
    progress: null,
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: [],
  },
  {
    id: "MR-0098",
    assetTag: "AR-000012",
    assetName: "Server Dell PowerEdge R750",
    reportedBy: "Raj Deshmukh",
    department: "Engineering",
    issueTitle: "RAID controller battery warning",
    issueDescription: "iDRAC reporting RAID controller battery degraded warning. Backup power for cache may fail. Backup scheduled nightly.",
    priority: "High",
    category: "Hardware Failure",
    status: "Pending",
    createdAt: "2026-07-09T08:00:00Z",
    approvedAt: null,
    approvedBy: null,
    rejectionReason: null,
    technician: null,
    technicianAssignedAt: null,
    estimatedCompletion: null,
    repairNotes: null,
    spareParts: null,
    progress: null,
    workStartedAt: null,
    resolvedAt: null,
    resolutionSummary: null,
    finalNotes: null,
    repairCost: null,
    conditionAfter: null,
    attachments: ["idrac-warning.png"],
  },
  {
    id: "MR-0099",
    assetTag: "AR-000003",
    assetName: "CNC Machine Model X",
    reportedBy: "Raj Deshmukh",
    department: "Operations",
    issueTitle: "Annual calibration overdue",
    issueDescription: "Scheduled annual calibration for CNC machine is overdue by 2 weeks. Machine accuracy may drift.",
    priority: "Low",
    category: "Performance Issue",
    status: "Resolved",
    createdAt: "2026-01-15T09:00:00Z",
    approvedAt: "2026-01-15T10:00:00Z",
    approvedBy: "Asset Manager",
    rejectionReason: null,
    technician: "Raj Deshmukh",
    technicianAssignedAt: "2026-01-15T11:00:00Z",
    estimatedCompletion: "2026-01-18",
    repairNotes: "Full calibration including spindle alignment, axis offsets, and tool setter.",
    spareParts: "None required",
    progress: "Completed",
    workStartedAt: "2026-01-16T08:00:00Z",
    resolvedAt: "2026-01-18T15:00:00Z",
    resolutionSummary: "Calibrated to ±0.005mm tolerance. All axes within spec.",
    finalNotes: "Machine running within normal parameters. Next calibration due Jan 2027.",
    repairCost: 1200,
    conditionAfter: "Excellent",
    attachments: ["calibration-report.pdf"],
  },
];

export const MOCK_TIMELINE: Record<string, MaintenanceTimelineEvent[]> = {
  "MR-0094": [
    { id: "TL-1", type: "reported", title: "Issue Reported", description: "Battery draining rapidly reported by Sarah Chen", date: "2026-07-03T11:00:00Z", user: "Sarah Chen" },
    { id: "TL-2", type: "approved", title: "Request Approved", description: "Maintenance request approved by Asset Manager", date: "2026-07-03T14:00:00Z", user: "Asset Manager" },
    { id: "TL-3", type: "technician_assigned", title: "Technician Assigned", description: "Assigned to Internal IT Support. Battery replacement authorized.", date: "2026-07-04T09:00:00Z", user: "Asset Manager" },
    { id: "TL-4", type: "progress_update", title: "Repair Started", description: "Device received. Battery replacement in progress.", date: "2026-07-08T10:00:00Z", user: "IT Support" },
  ],
  "MR-0093": [
    { id: "TL-10", type: "reported", title: "Critical Issue Reported", description: "Spindle bearing failure - machine shut down for safety", date: "2026-07-05T08:30:00Z", user: "Operator" },
    { id: "TL-11", type: "approved", title: "Request Approved", description: "Emergency approval granted", date: "2026-07-05T10:00:00Z", user: "Asset Manager" },
    { id: "TL-12", type: "technician_assigned", title: "External Service Assigned", description: "Haas Service scheduled for on-site visit", date: "2026-07-05T14:00:00Z", user: "Asset Manager" },
  ],
  "MR-0096": [
    { id: "TL-20", type: "reported", title: "Issue Reported", description: "Frequent paper jams reported", date: "2026-06-25T09:00:00Z", user: "Lisa Park" },
    { id: "TL-21", type: "approved", title: "Request Approved", description: "Approved for internal repair", date: "2026-06-25T11:00:00Z", user: "Asset Manager" },
    { id: "TL-22", type: "technician_assigned", title: "Technician Assigned", description: "Assigned to IT Support", date: "2026-06-26T09:00:00Z", user: "Asset Manager" },
    { id: "TL-23", type: "progress_update", title: "Repair Started", description: "Device inspected, rollers showing wear", date: "2026-06-28T10:00:00Z", user: "IT Support" },
    { id: "TL-24", type: "resolved", title: "Repair Resolved", description: "Pickup rollers and separator pad replaced", date: "2026-06-28T14:00:00Z", user: "IT Support" },
    { id: "TL-25", type: "available", title: "Asset Available", description: "Printer returned to service. 200-page test clean.", date: "2026-06-28T14:30:00Z", user: "System" },
  ],
};
