import type { Resource, Booking } from "./types";

export const DEPARTMENTS = [
  "Engineering",
  "Finance",
  "HR",
  "Marketing",
  "Operations",
  "Procurement",
  "Sales",
  "IT",
];

export const RESOURCES: Resource[] = [
  { id: "r1", name: "Conference Room A", type: "Meeting Room", capacity: "12 people", location: "Floor 1, Wing A", available: true, icon: "Building" },
  { id: "r2", name: "Meeting Room B2", type: "Meeting Room", capacity: "6 people", location: "Floor 2, Wing B", available: true, icon: "Building" },
  { id: "r3", name: "Board Room", type: "Meeting Room", capacity: "20 people", location: "Floor 1, Board Wing", available: false, icon: "Building" },
  { id: "r4", name: "Huddle Room 1", type: "Meeting Room", capacity: "4 people", location: "Floor 3, Wing A", available: true, icon: "Building" },
  { id: "r5", name: "Projector Epson EB-X51", type: "Equipment", capacity: "N/A", location: "AV Storage, Floor 1", available: true, icon: "Monitor" },
  { id: "r6", name: "Conference Speaker Set", type: "Equipment", capacity: "N/A", location: "AV Storage, Floor 1", available: false, icon: "Speaker" },
  { id: "r7", name: "Toyota Hilux (VH-04)", type: "Vehicle", capacity: "5 passengers", location: "Parking B1", available: true, icon: "Car" },
  { id: "r8", name: "Honda Civic (VH-07)", type: "Vehicle", capacity: "5 passengers", location: "Parking B1", available: true, icon: "Car" },
  { id: "r9", name: "Training Lab", type: "Training Room", capacity: "30 people", location: "Floor 4, Room 401", available: true, icon: "GraduationCap" },
  { id: "r10", name: "Workshop Room", type: "Training Room", capacity: "15 people", location: "Floor 4, Room 403", available: true, icon: "GraduationCap" },
];

export const MOCK_BOOKINGS: Booking[] = [
  // Upcoming
  {
    id: "BK-401",
    resourceId: "r1",
    resourceName: "Conference Room A",
    resourceType: "Meeting Room",
    booker: "Sarah Chen",
    department: "Engineering",
    date: "2026-07-15",
    startTime: "09:00",
    endTime: "10:30",
    purpose: "Sprint planning meeting",
    participants: ["Raj Deshmukh", "Jordan Lee"],
    status: "Upcoming",
    reminderSent: false,
  },
  {
    id: "BK-402",
    resourceId: "r2",
    resourceName: "Meeting Room B2",
    resourceType: "Meeting Room",
    booker: "Marcus Webb",
    department: "Procurement",
    date: "2026-07-15",
    startTime: "14:00",
    endTime: "15:00",
    purpose: "Vendor review meeting",
    participants: ["Nina Petrov"],
    status: "Upcoming",
    reminderSent: false,
  },
  {
    id: "BK-403",
    resourceId: "r7",
    resourceName: "Toyota Hilux (VH-04)",
    resourceType: "Vehicle",
    booker: "Priya Sharma",
    department: "Marketing",
    date: "2026-07-16",
    startTime: "08:00",
    endTime: "17:00",
    purpose: "Client site visit in suburban area",
    participants: [],
    status: "Upcoming",
    reminderSent: false,
  },
  {
    id: "BK-404",
    resourceId: "r5",
    resourceName: "Projector Epson EB-X51",
    resourceType: "Equipment",
    booker: "Jordan Lee",
    department: "Operations",
    date: "2026-07-17",
    startTime: "10:00",
    endTime: "12:00",
    purpose: "Quarterly ops review presentation",
    participants: ["Kim Tanaka", "Alex Rivera"],
    status: "Upcoming",
    reminderSent: false,
  },
  {
    id: "BK-405",
    resourceId: "r9",
    resourceName: "Training Lab",
    resourceType: "Training Room",
    booker: "Alex Rivera",
    department: "HR",
    date: "2026-07-18",
    startTime: "09:00",
    endTime: "17:00",
    purpose: "New hire orientation program",
    participants: ["Lisa Park", "David Kim"],
    status: "Upcoming",
    reminderSent: false,
  },
  // Ongoing
  {
    id: "BK-410",
    resourceId: "r3",
    resourceName: "Board Room",
    resourceType: "Meeting Room",
    booker: "Nina Petrov",
    department: "Finance",
    date: "2026-07-12",
    startTime: "09:00",
    endTime: "17:00",
    purpose: "Board meeting - Q3 financials review",
    participants: ["Sarah Chen", "Marcus Webb"],
    status: "Ongoing",
    reminderSent: true,
  },
  {
    id: "BK-411",
    resourceId: "r6",
    resourceName: "Conference Speaker Set",
    resourceType: "Equipment",
    booker: "David Kim",
    department: "Sales",
    date: "2026-07-12",
    startTime: "13:00",
    endTime: "16:00",
    purpose: "Client presentation setup",
    participants: ["Priya Sharma"],
    status: "Ongoing",
    reminderSent: true,
  },
  // Completed
  {
    id: "BK-420",
    resourceId: "r1",
    resourceName: "Conference Room A",
    resourceType: "Meeting Room",
    booker: "Raj Deshmukh",
    department: "Engineering",
    date: "2026-07-10",
    startTime: "10:00",
    endTime: "11:30",
    purpose: "Architecture review session",
    participants: ["Sarah Chen", "Jordan Lee"],
    status: "Completed",
    reminderSent: true,
  },
  {
    id: "BK-421",
    resourceId: "r2",
    resourceName: "Meeting Room B2",
    resourceType: "Meeting Room",
    booker: "Alex Rivera",
    department: "HR",
    date: "2026-07-09",
    startTime: "14:00",
    endTime: "15:00",
    purpose: "Performance review discussion",
    participants: [],
    status: "Completed",
    reminderSent: true,
  },
  {
    id: "BK-422",
    resourceId: "r7",
    resourceName: "Toyota Hilux (VH-04)",
    resourceType: "Vehicle",
    booker: "Marcus Webb",
    department: "Procurement",
    date: "2026-07-08",
    startTime: "08:00",
    endTime: "16:00",
    purpose: "Supplier warehouse visit",
    participants: ["Kim Tanaka"],
    status: "Completed",
    reminderSent: true,
  },
  {
    id: "BK-423",
    resourceId: "r5",
    resourceName: "Projector Epson EB-X51",
    resourceType: "Equipment",
    booker: "Priya Sharma",
    department: "Marketing",
    date: "2026-07-07",
    startTime: "09:00",
    endTime: "12:00",
    purpose: "Brand strategy presentation",
    participants: ["Nina Petrov", "Lisa Park"],
    status: "Completed",
    reminderSent: true,
  },
  // Cancelled
  {
    id: "BK-430",
    resourceId: "r4",
    resourceName: "Huddle Room 1",
    resourceType: "Meeting Room",
    booker: "Jordan Lee",
    department: "Operations",
    date: "2026-07-09",
    startTime: "11:00",
    endTime: "12:00",
    purpose: "Team sync - cancelled due to emergency",
    participants: ["Kim Tanaka"],
    status: "Cancelled",
    reminderSent: true,
  },
  {
    id: "BK-431",
    resourceId: "r8",
    resourceName: "Honda Civic (VH-07)",
    resourceType: "Vehicle",
    booker: "David Kim",
    department: "Sales",
    date: "2026-07-06",
    startTime: "09:00",
    endTime: "13:00",
    purpose: "Client meeting - rescheduled",
    participants: [],
    status: "Cancelled",
    reminderSent: true,
  },
  {
    id: "BK-432",
    resourceId: "r9",
    resourceName: "Training Lab",
    resourceType: "Training Room",
    booker: "Alex Rivera",
    department: "HR",
    date: "2026-07-04",
    startTime: "10:00",
    endTime: "15:00",
    purpose: "Workshop postponed to next week",
    participants: ["Lisa Park"],
    status: "Cancelled",
    reminderSent: true,
  },
];

export const TIME_SLOTS = [
  "08:00", "08:30", "09:00", "09:30", "10:00", "10:30",
  "11:00", "11:30", "12:00", "12:30", "13:00", "13:30",
  "14:00", "14:30", "15:00", "15:30", "16:00", "16:30",
  "17:00", "17:30", "18:00",
];
