import type {
  Allocation,
  TransferRequest,
  ApprovalRequest,
  OverdueItem,
  HistoryEvent,
  AvailableAsset,
  Employee,
} from "./types";

export const DEPARTMENTS = [
  "Engineering",
  "Finance",
  "HR",
  "Marketing",
  "Operations",
  "Procurement",
  "Sales",
  "IT",
];

export const AVAILABLE_ASSETS: AvailableAsset[] = [
  { id: "2", tag: "AR-000002", name: "Dell UltraSharp 27\" Monitor", department: "Finance", location: "Floor 2, Wing B" },
  { id: "8", tag: "AR-000008", name: "HP LaserJet Enterprise M611", department: "Finance", location: "Floor 2, Copy Room" },
  { id: "10", tag: "AR-000010", name: "Standing Desk Ergo Pro", department: "Engineering", location: "Floor 3, Wing A" },
  { id: "14", tag: "AR-000014", name: "Logitech Rally 4K Camera", department: "Marketing", location: "Floor 2, Meeting Room B" },
  { id: "16", tag: "AR-000016", name: "3D Printer Ultimaker S7", department: "Engineering", location: "Innovation Lab, Room 301" },
];

export const ALLOCATED_ASSETS: AvailableAsset[] = [
  { id: "1", tag: "AR-000001", name: 'MacBook Pro 16"', department: "Engineering", location: "Floor 3, Wing A" },
  { id: "5", tag: "AR-000005", name: "Herman Miller Aeron Chair", department: "HR", location: "Floor 2, Wing A" },
  { id: "6", tag: "AR-000006", name: "Toyota Hilux Revo", department: "Procurement", location: "Parking Level B1" },
  { id: "9", tag: "AR-000009", name: 'iPad Pro 12.9"', department: "Marketing", location: "Floor 3, Wing B" },
  { id: "11", tag: "AR-000011", name: "Cisco Webex Board Pro 75", department: "Operations", location: "Floor 1, Meeting Room A" },
  { id: "12", tag: "AR-000012", name: "Server Dell PowerEdge R750", department: "Engineering", location: "Server Room, Rack 4" },
  { id: "13", tag: "AR-000013", name: "Forklift Toyota 8FGU25", department: "Operations", location: "Warehouse A" },
  { id: "17", tag: "AR-000017", name: "Conference Phone Poly Trio C60", department: "Finance", location: "Floor 2, Meeting Room C" },
];

export const EMPLOYEES: Employee[] = [
  { id: "e1", name: "Sarah Chen", department: "Engineering", email: "sarah@company.com" },
  { id: "e2", name: "Marcus Webb", department: "Procurement", email: "marcus@company.com" },
  { id: "e3", name: "Alex Rivera", department: "HR", email: "alex@company.com" },
  { id: "e4", name: "Priya Sharma", department: "Marketing", email: "priya@company.com" },
  { id: "e5", name: "Jordan Lee", department: "Operations", email: "jordan@company.com" },
  { id: "e6", name: "Kim Tanaka", department: "Operations", email: "kim@company.com" },
  { id: "e7", name: "Raj Deshmukh", department: "Engineering", email: "raj@company.com" },
  { id: "e8", name: "Nina Petrov", department: "Finance", email: "nina@company.com" },
  { id: "e9", name: "David Kim", department: "Sales", email: "david@company.com" },
  { id: "e10", name: "Lisa Park", department: "Finance", email: "lisa@company.com" },
];

export const MOCK_ALLOCATIONS: Allocation[] = [
  {
    id: "ALLOC-101",
    assetTag: "AR-000001",
    assetName: 'MacBook Pro 16"',
    employee: "Sarah Chen",
    department: "Engineering",
    allocatedDate: "2025-09-20",
    expectedReturn: "2026-09-20",
    actualReturnDate: null,
    status: "Active",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-102",
    assetTag: "AR-000005",
    assetName: "Herman Miller Aeron Chair",
    employee: "Alex Rivera",
    department: "HR",
    allocatedDate: "2025-08-15",
    expectedReturn: "2026-08-15",
    actualReturnDate: null,
    status: "Active",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-103",
    assetTag: "AR-000006",
    assetName: "Toyota Hilux Revo",
    employee: "Marcus Webb",
    department: "Procurement",
    allocatedDate: "2024-03-01",
    expectedReturn: "2026-07-01",
    actualReturnDate: null,
    status: "Overdue",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-104",
    assetTag: "AR-000009",
    assetName: 'iPad Pro 12.9"',
    employee: "Priya Sharma",
    department: "Marketing",
    allocatedDate: "2025-12-10",
    expectedReturn: "2026-07-20",
    actualReturnDate: null,
    status: "Due Soon",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-105",
    assetTag: "AR-000011",
    assetName: "Cisco Webex Board Pro 75",
    employee: "Jordan Lee",
    department: "Operations",
    allocatedDate: "2025-08-01",
    expectedReturn: "2026-08-01",
    actualReturnDate: null,
    status: "Active",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-106",
    assetTag: "AR-000012",
    assetName: "Server Dell PowerEdge R750",
    employee: "Raj Deshmukh",
    department: "Engineering",
    allocatedDate: "2024-07-01",
    expectedReturn: "2027-07-01",
    actualReturnDate: null,
    status: "Active",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-107",
    assetTag: "AR-000013",
    assetName: "Forklift Toyota 8FGU25",
    employee: "Kim Tanaka",
    department: "Operations",
    allocatedDate: "2023-01-15",
    expectedReturn: "2026-01-15",
    actualReturnDate: null,
    status: "Overdue",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-108",
    assetTag: "AR-000017",
    assetName: "Conference Phone Poly Trio C60",
    employee: "Nina Petrov",
    department: "Finance",
    allocatedDate: "2025-10-01",
    expectedReturn: "2026-10-01",
    actualReturnDate: null,
    status: "Active",
    condition: null,
    returnNotes: null,
  },
  {
    id: "ALLOC-098",
    assetTag: "AR-000002",
    assetName: "Dell UltraSharp 27\" Monitor",
    employee: "Lisa Park",
    department: "Finance",
    allocatedDate: "2025-06-01",
    expectedReturn: "2026-01-01",
    actualReturnDate: "2025-12-20",
    status: "Returned",
    condition: "Good",
    returnNotes: "Minor scratch on bezel, otherwise fine",
  },
  {
    id: "ALLOC-095",
    assetTag: "AR-000008",
    assetName: "HP LaserJet Enterprise M611",
    employee: "David Kim",
    department: "Sales",
    allocatedDate: "2025-03-01",
    expectedReturn: "2025-09-01",
    actualReturnDate: "2025-08-28",
    status: "Returned",
    condition: "Good",
    returnNotes: "Returned on time, working perfectly",
  },
];

export const MOCK_TRANSFERS: TransferRequest[] = [
  {
    id: "TRF-201",
    assetTag: "AR-000004",
    assetName: "Projector Epson EB-L1755U",
    fromEmployee: "Alex Rivera",
    fromDepartment: "HR",
    toEmployee: "Priya Sharma",
    toDepartment: "Marketing",
    reason: "Marketing needs projector for upcoming product launch event in August",
    requestDate: "2026-07-08",
    status: "Pending",
    departmentHeadApproval: false,
    assetManagerApproval: false,
  },
  {
    id: "TRF-202",
    assetTag: "AR-000008",
    assetName: "HP LaserJet Enterprise M611",
    fromEmployee: "Nina Petrov",
    fromDepartment: "Finance",
    toEmployee: "Alex Rivera",
    toDepartment: "HR",
    reason: "HR department requires dedicated printer for confidential employee documents",
    requestDate: "2026-07-09",
    status: "Approved",
    departmentHeadApproval: true,
    assetManagerApproval: true,
  },
  {
    id: "TRF-203",
    assetTag: "AR-000005",
    assetName: "Herman Miller Aeron Chair",
    fromEmployee: "Jordan Lee",
    fromDepartment: "Operations",
    toEmployee: "Sarah Chen",
    toDepartment: "Engineering",
    reason: "Ergonomic chair needed for developer workstation",
    requestDate: "2026-07-10",
    status: "Rejected",
    departmentHeadApproval: false,
    assetManagerApproval: false,
  },
  {
    id: "TRF-204",
    assetTag: "AR-000014",
    assetName: "Logitech Rally 4K Camera",
    fromEmployee: "Marcus Webb",
    fromDepartment: "Procurement",
    toEmployee: "Jordan Lee",
    toDepartment: "Operations",
    reason: "Operations needs camera for conference room upgrades",
    requestDate: "2026-07-11",
    status: "Pending",
    departmentHeadApproval: true,
    assetManagerApproval: false,
  },
];

export const MOCK_APPROVALS: ApprovalRequest[] = [
  {
    id: "APR-301",
    type: "transfer",
    assetTag: "AR-000004",
    assetName: "Projector Epson EB-L1755U",
    requestedBy: "Priya Sharma",
    department: "Marketing",
    requestDate: "2026-07-08",
    details: "Transfer from HR to Marketing for product launch event",
    status: "Pending",
  },
  {
    id: "APR-302",
    type: "return",
    assetTag: "AR-000009",
    assetName: 'iPad Pro 12.9"',
    requestedBy: "Priya Sharma",
    department: "Marketing",
    requestDate: "2026-07-10",
    details: "Requesting 2-week extension — project deadline moved to Aug 3",
    status: "Pending",
  },
  {
    id: "APR-303",
    type: "extension",
    assetTag: "AR-000001",
    assetName: 'MacBook Pro 16"',
    requestedBy: "Sarah Chen",
    department: "Engineering",
    requestDate: "2026-07-09",
    details: "Need to extend allocation by 3 months for Q4 project work",
    status: "Pending",
  },
];

export const MOCK_OVERDUE: OverdueItem[] = [
  {
    id: "OD-001",
    assetTag: "AR-000006",
    assetName: "Toyota Hilux Revo",
    employee: "Marcus Webb",
    department: "Procurement",
    expectedReturn: "2026-07-01",
    daysOverdue: 11,
    priority: "critical",
  },
  {
    id: "OD-002",
    assetTag: "AR-000013",
    assetName: "Forklift Toyota 8FGU25",
    employee: "Kim Tanaka",
    department: "Operations",
    expectedReturn: "2026-01-15",
    daysOverdue: 178,
    priority: "critical",
  },
];

export const MOCK_HISTORY: HistoryEvent[] = [
  { id: "H-001", type: "allocated", assetTag: "AR-000001", assetName: 'MacBook Pro 16"', to: "Sarah Chen", department: "Engineering", date: "2025-09-20", user: "System Admin", notes: "Initial allocation" },
  { id: "H-002", type: "allocated", assetTag: "AR-000005", assetName: "Herman Miller Aeron Chair", to: "Alex Rivera", department: "HR", date: "2025-08-15", user: "HR Admin" },
  { id: "H-003", type: "transferred", assetTag: "AR-000008", assetName: "HP LaserJet Enterprise M611", from: "David Kim", to: "Nina Petrov", department: "Finance", date: "2025-09-01", user: "Asset Manager" },
  { id: "H-004", type: "returned", assetTag: "AR-000002", assetName: "Dell UltraSharp 27\" Monitor", from: "Lisa Park", department: "Finance", date: "2025-12-20", user: "Lisa Park", notes: "Minor scratch on bezel" },
  { id: "H-005", type: "allocated", assetTag: "AR-000006", assetName: "Toyota Hilux Revo", to: "Marcus Webb", department: "Procurement", date: "2024-03-01", user: "System Admin" },
  { id: "H-006", type: "extended", assetTag: "AR-000011", assetName: "Cisco Webex Board Pro 75", to: "Jordan Lee", department: "Operations", date: "2026-06-01", user: "Asset Manager", notes: "Extended by 6 months" },
  { id: "H-007", type: "transferred", assetTag: "AR-000014", assetName: "Logitech Rally 4K Camera", from: "Marcus Webb", to: "Jordan Lee", department: "Operations", date: "2026-07-02", user: "Asset Manager" },
  { id: "H-008", type: "returned", assetTag: "AR-000008", assetName: "HP LaserJet Enterprise M611", from: "David Kim", department: "Sales", date: "2025-08-28", user: "David Kim", notes: "Working perfectly" },
  { id: "H-009", type: "allocated", assetTag: "AR-000009", assetName: 'iPad Pro 12.9"', to: "Priya Sharma", department: "Marketing", date: "2025-12-10", user: "System Admin" },
  { id: "H-010", type: "allocated", assetTag: "AR-000013", assetName: "Forklift Toyota 8FGU25", to: "Kim Tanaka", department: "Operations", date: "2023-01-15", user: "System Admin" },
];
